-- Expand CallLeadStatus for sheet workflow labels
ALTER TYPE "CallLeadStatus" ADD VALUE IF NOT EXISTS 'NO_ANSWER_OVER_50';
ALTER TYPE "CallLeadStatus" ADD VALUE IF NOT EXISTS 'FUTURE_HIRE';
ALTER TYPE "CallLeadStatus" ADD VALUE IF NOT EXISTS 'REFERRAL_NOT_AVAILABLE';
